### PR TITLE
Updates to mgt

### PR DESCRIPTION
**Pull request by jrspinella**
Updates to Mg/Budgets
Updates to TF State
Restructure of files

### CODE REVIEW

**Comment by CurtisSlone** [comment]
Uh-Oh. Waiting on those checks

**Comment by jrspinella** [comment]
> Uh-Oh. Waiting on those checks

Yeah, bare with me. trying to get workflows right.

**Comment by CurtisSlone** [comment]
Got time for a call?

**Comment by jrspinella** [comment]
> Got time for a call?

in a hour...

**Review by CurtisSlone — APPROVED** [review]
Doing God's Work

**Pull request merged**
